### ISSUE TITLE
Implement an interface for users to keep track of their pets

### ISSUE THREAD

**Issue by olgunataberk** [GitBusting/BorkinRoads#1]
This issue can be summarized under three bullets:

* Create a view that lists the registered pets of the user
* Create a view displaying various info about one pet
* Let users take or upload photos for their pets

**Comment by punoqun** [comment]
- f7bb181 prints the information about pets to the screen
- a6f43f8 adds new pets
- df30baf handles app navigation
- 45e5099 lists and switches between pets

which concludes and closes this issue
