### ISSUE TITLE
Let users review their walking routes

### ISSUE THREAD

**Issue by olgunataberk** [GitBusting/BorkinRoads#2]
Implement various views to let users rate their previous routes, display their previous walking routes and display their favorite routes

**Comment by utkuumur** [comment]
- [a250a1e](https://github.com/GitBusting/BorkinRoads/commit/a250a1eb7352d4e2062ebdb838f95505653320b2), [2c7efe7](https://github.com/GitBusting/BorkinRoads/commit/2c7efe74f8278930bf759e68b160a620b1e1433c), [a705372](https://github.com/GitBusting/BorkinRoads/commit/a7053720fd770d662cbed60b924f634c803629c4)  and [dbb4bbc](https://github.com/GitBusting/BorkinRoads/commit/dbb4bbce26bd7847c686b6d921c6202253d3349e) creates list for displaying routes
- [9644cfb](https://github.com/GitBusting/BorkinRoads/commit/9644cfb1992df6b6b331df6943408327bbdffaaf), [c5ae11](https://github.com/GitBusting/BorkinRoads/commit/c5ae11e8892f88fab874752d5a882302d5fd5f57) and [2e3382d](https://github.com/GitBusting/BorkinRoads/commit/2e3382d54081b5e69b1523e7f677c28c3792e6e6) implements basic favourites filtering
- [1d6086d](https://github.com/GitBusting/BorkinRoads/commit/1d6086dd95a96f8a1ca263e85e37836bb3f2f2fd), [b409e3d](https://github.com/GitBusting/BorkinRoads/commit/b409e3d5390556c0b8bc135b65f4d9bc891ccc9a) and [bd1e06b](https://github.com/GitBusting/BorkinRoads/commit/bd1e06bf233668d58cb97a3c6fc02a2e11f1aa77) expands filter options for routes are close to water/lake/river or forest/park
- [7170a44](https://github.com/GitBusting/BorkinRoads/commit/7170a44ef528727c2cb6aad79eee4f9b46e97b53) and [808af89](https://github.com/GitBusting/BorkinRoads/commit/808af8902d01437c8dda9552324d86b091bbc535) makes filter options collapsable and other gui updates
- [82b4ff5](https://github.com/GitBusting/BorkinRoads/commit/82b4ff5e30772f47f2209f5a821637367531e700) Makes filtering dynamic and implement sorting
